### ISSUE TITLE
Faces Detecting 

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/SAVI_Face_Recognition#1]

**Comment by andrefdre** [comment]
After some research I found this link that explains the methods for face detecting and what are the advantages of each method: 
https://www.superdatascience.com/blogs/opencv-face-detection

From what I read the Haar method is the best option because it has the better accuracy the only disadvantage is that it is slower to train the model some problems with different light.

**Comment by LimitlessGrey** [comment]
What is the difference between face recog. and face detect?
