### ISSUE TITLE
Body Recog/Tracking

### ISSUE THREAD

**Issue by LimitlessGrey** [andrefdre/SAVI_Face_Recognition#12]
https://github.com/Its-Triggy/Joint_Track/blob/master/jointTrack.py

Found this (apparently ineficient) code to perform body tracking. It seems it uses a system of joints and branches and recognizes the body as such

**Comment by andrefdre** [comment]
Do you think that method will be fast enough, I mean not leave the showing of images very slow?

**Comment by LimitlessGrey** [comment]
No idea. The code itself runs quite well alone.. Im not sure if it would do the same when implemented together with what we have already. We can try it :)

**Comment by andrefdre** [comment]
Okay seems like a good next step for now.

**Comment by LimitlessGrey** [comment]
Just did tracking of the body where it recognizes it as a skeleton (hands included). can you help me pass it to a class in functions @andrefdre, please?

**Comment by LimitlessGrey** [comment]
Forgot to add: this holistic model to track the body moving requires to install mediapipe via pip : !pip install mediapip (! may or may not be necessary)

**Comment by andrefdre** [comment]
I found a good method of recognizing bodies that works very well and I was able to implement it replacing the Haar Cascade. I based my code on this repository https://github.com/Kazuhito00/Person-Detection-using-RaspberryPi-CPU/blob/main/README_EN.md.
