### ISSUE TITLE
Implementing multiple body recognition 

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/SAVI_Face_Recognition#14]
One of the problems we have is that a feature to recognize body only works for one and we need it to implement multiple. My approach will be to first use haarcascades to detect body and then in that Bounding boxes I will apply the code to track the body.

**Comment by LimitlessGrey** [comment]
So create detections for the body? And apply media pipe on it?

**Comment by andrefdre** [comment]
Basically that's my idea, if you have two people with you could you go to my new branch and try it out cause right now cannot try it and I think it should work.
I also changed the face tracking to upper body tracking and disabled the recognition for now cause it needs some updates to work with this.
