### ISSUE TITLE
Faces Tracking

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/SAVI_Face_Recognition#2]

**Comment by LimitlessGrey** [comment]
Object tracking check bbox and some more stuff

https://pysource.com/2021/01/28/object-tracking-with-opencv-and-python/

**Comment by LimitlessGrey** [comment]
Pysource YT Tutorial

https://www.youtube.com/watch?v=O3b8lVF93jU&t=812s&ab_channel=Pysource

**Comment by andrefdre** [comment]
I finished implementing the tracker and detection of the face that @LimitlessGrey did and now we need to do some research to decide which tracker model is better and also we need to implement the body detection and tracker and only then face will be detected.

**Comment by LimitlessGrey** [comment]
Recomend the CSRT Tracker. Albeit slower it is very reliable when used with cameras that record with 25 or less FPS

**Comment by andrefdre** [comment]
We need to perform some tests cause I'm having a problem of the tracking when they don't detect they disappear and I think it's not what is suppose to happen.
And I already changed the tracking method to the one suggested by @LimitlessGrey.

**Comment by andrefdre** [comment]
This is implemented and for now is working fine. Next step is moving this code so it tracks bodys instead of faces.
