### ISSUE TITLE
Greeting the people the database knows

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/SAVI_Face_Recognition#5]

**Comment by LimitlessGrey** [comment]
@Contin1999  Can you please push the file with the Speech to text that you showed me yesterday?

**Comment by andrefdre** [comment]
Requeriments that I needed to install to run this code:
`sudo apt-get install alsa-utils`
`pip3 install pyttsx3`
` sudo apt install espeak`
` sudo apt install python3-pyaudio`

**Comment by andrefdre** [comment]
This was added to the main code, but still needs some work. When it's greeting it gets very slow so @Contin1999 could you research about that?

**Comment by Contin1999** [comment]
ok i've fixed the problem, now i have to "commit" right?
